# Generated by Django 3.1.2 on 2020-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=60)),
                ('destination', models.CharField(max_length=60)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
